# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QEvent, pyqtSignal, QSize
from PyQt5.QtWidgets import QApplication

PLAYCHESS_PKG_DIR = '/home/luca/tiago_public_ws/src/tiago_playchess'
GUI_PKG_DIR       = '/home/luca/tiago_public_ws/src/chess_gui'

class Ui_Chessboard_Black(object):
    def setupUi(self, Chessboard, app):
        Chessboard.setObjectName("Chessboard")
        Chessboard.resize(677, 635)
        Chessboard.setMinimumSize(QtCore.QSize(0, 70))
        Chessboard.setMaximumSize(QtCore.QSize(677, 16777215))
        self.icon_Wpawn_b = QtGui.QIcon()
        self.icon_Wpawn_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Pawn_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wknight_b = QtGui.QIcon()
        self.icon_Wknight_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Knight_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wbishop_b = QtGui.QIcon()
        self.icon_Wbishop_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Bishop_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wqueen_b = QtGui.QIcon()
        self.icon_Wqueen_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Queen_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wking_b = QtGui.QIcon()
        self.icon_Wking_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_King_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wrook_b = QtGui.QIcon()
        self.icon_Wrook_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Rook_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bpawn_b = QtGui.QIcon()
        self.icon_Bpawn_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Pawn_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bknight_b = QtGui.QIcon()
        self.icon_Bknight_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Knight_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bbishop_b = QtGui.QIcon()
        self.icon_Bbishop_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Bishop_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bqueen_b = QtGui.QIcon()
        self.icon_Bqueen_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Queen_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bking_b = QtGui.QIcon()
        self.icon_Bking_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_King_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Brook_b = QtGui.QIcon()
        self.icon_Brook_b.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Rook_b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wpawn_w = QtGui.QIcon()
        self.icon_Wpawn_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Pawn_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wknight_w = QtGui.QIcon()
        self.icon_Wknight_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Knight_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wbishop_w = QtGui.QIcon()
        self.icon_Wbishop_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Bishop_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wqueen_w = QtGui.QIcon()
        self.icon_Wqueen_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Queen_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wking_w = QtGui.QIcon()
        self.icon_Wking_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_King_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wrook_w = QtGui.QIcon()
        self.icon_Wrook_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Rook_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bpawn_w = QtGui.QIcon()
        self.icon_Bpawn_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Pawn_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bknight_w = QtGui.QIcon()
        self.icon_Bknight_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Knight_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bbishop_w = QtGui.QIcon()
        self.icon_Bbishop_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Bishop_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bqueen_w = QtGui.QIcon()
        self.icon_Bqueen_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Queen_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bking_w = QtGui.QIcon()
        self.icon_Bking_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_King_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Brook_w = QtGui.QIcon()
        self.icon_Brook_w.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Rook_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_grey = QtGui.QIcon()
        self.icon_grey.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/grey.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red = QtGui.QIcon()
        self.icon_red.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/red.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #Icons with red background (selected squares)
        self.icon_red_Wpawn = QtGui.QIcon()
        self.icon_red_Wpawn.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Pawn_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Bpawn = QtGui.QIcon()
        self.icon_red_Bpawn.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Pawn_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Wrook = QtGui.QIcon()
        self.icon_red_Wrook.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Rook_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Brook = QtGui.QIcon()
        self.icon_red_Brook.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Rook_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Wknight = QtGui.QIcon()
        self.icon_red_Wknight.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Knight_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Bknight = QtGui.QIcon()
        self.icon_red_Bknight.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Knight_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Wbishop = QtGui.QIcon()
        self.icon_red_Wbishop.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Bishop_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Bbishop = QtGui.QIcon()
        self.icon_red_Bbishop.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Bishop_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Wqueen = QtGui.QIcon()
        self.icon_red_Wqueen.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Queen_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Bqueen = QtGui.QIcon()
        self.icon_red_Bqueen.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Queen_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Wking = QtGui.QIcon()
        self.icon_red_Wking.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_King_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_red_Bking = QtGui.QIcon()
        self.icon_red_Bking.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_King_r.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #Icons with red selection (squares with focus on)
        self.icon_Wpawn_b_frame = QtGui.QIcon()
        self.icon_Wpawn_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Pawn_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wknight_b_frame = QtGui.QIcon()
        self.icon_Wknight_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Knight_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wbishop_b_frame = QtGui.QIcon()
        self.icon_Wbishop_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Bishop_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wqueen_b_frame = QtGui.QIcon()
        self.icon_Wqueen_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Queen_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wking_b_frame = QtGui.QIcon()
        self.icon_Wking_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_King_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wrook_b_frame = QtGui.QIcon()
        self.icon_Wrook_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Rook_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bpawn_b_frame = QtGui.QIcon()
        self.icon_Bpawn_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Pawn_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bknight_b_frame = QtGui.QIcon()
        self.icon_Bknight_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Knight_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bbishop_b_frame = QtGui.QIcon()
        self.icon_Bbishop_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Bishop_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bqueen_b_frame = QtGui.QIcon()
        self.icon_Bqueen_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Queen_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bking_b_frame = QtGui.QIcon()
        self.icon_Bking_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_King_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Brook_b_frame = QtGui.QIcon()
        self.icon_Brook_b_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Rook_b_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wpawn_w_frame = QtGui.QIcon()
        self.icon_Wpawn_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Pawn_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wknight_w_frame = QtGui.QIcon()
        self.icon_Wknight_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Knight_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wbishop_w_frame = QtGui.QIcon()
        self.icon_Wbishop_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Bishop_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wqueen_w_frame = QtGui.QIcon()
        self.icon_Wqueen_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Queen_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wking_w_frame = QtGui.QIcon()
        self.icon_Wking_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_King_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wrook_w_frame = QtGui.QIcon()
        self.icon_Wrook_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Rook_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bpawn_w_frame = QtGui.QIcon()
        self.icon_Bpawn_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Pawn_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bknight_w_frame = QtGui.QIcon()
        self.icon_Bknight_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Knight_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bbishop_w_frame = QtGui.QIcon()
        self.icon_Bbishop_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Bishop_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bqueen_w_frame = QtGui.QIcon()
        self.icon_Bqueen_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Queen_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bking_w_frame = QtGui.QIcon()
        self.icon_Bking_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_King_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Brook_w_frame = QtGui.QIcon()
        self.icon_Brook_w_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Rook_w_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_grey_frame = QtGui.QIcon()
        self.icon_grey_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/grey_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_white_frame = QtGui.QIcon()
        self.icon_white_frame.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/white_frame.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wpawn_y = QtGui.QIcon()
        self.icon_Wpawn_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Pawn_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bpawn_y = QtGui.QIcon()
        self.icon_Bpawn_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Pawn_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wrook_y = QtGui.QIcon()
        self.icon_Wrook_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Rook_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Brook_y = QtGui.QIcon()
        self.icon_Brook_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Rook_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wknight_y = QtGui.QIcon()
        self.icon_Wknight_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Knight_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bknight_y = QtGui.QIcon()
        self.icon_Bknight_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Knight_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wbishop_y = QtGui.QIcon()
        self.icon_Wbishop_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Bishop_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bbishop_y = QtGui.QIcon()
        self.icon_Bbishop_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Bishop_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wking_y = QtGui.QIcon()
        self.icon_Wking_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_King_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bking_y = QtGui.QIcon()
        self.icon_Bking_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_King_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Wqueen_y = QtGui.QIcon()
        self.icon_Wqueen_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/W_Queen_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_Bqueen_y = QtGui.QIcon()
        self.icon_Bqueen_y.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/B_Queen_y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gridLayout = QtWidgets.QGridLayout(Chessboard)
        self.gridLayout.setObjectName("gridLayout")
        self.h8 = QtWidgets.QPushButton(Chessboard)
        self.h8.setMinimumSize(QtCore.QSize(70, 70))
        self.h8.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.h8.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/white_rook.png);")
        self.h8.setIcon(self.icon_Brook_b)
        self.h8.setIconSize(QtCore.QSize(65, 65))
        self.h8.setText("")
        self.h8.setCheckable(True)
        self.h8.setChecked(False)
        self.h8.setAutoExclusive(True)
        self.h8.setObjectName("h8")
        self.h8.setFocus() #Set the initial focus of the GUI on the h8 square
        self.current_focus = 'h8'
        self.gridLayout.addWidget(self.h8, 7, 0, 1, 1)
        self.g8 = QtWidgets.QPushButton(Chessboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(70)
        sizePolicy.setHeightForWidth(self.g8.sizePolicy().hasHeightForWidth())
        self.g8.setSizePolicy(sizePolicy)
        self.g8.setMinimumSize(QtCore.QSize(70, 70))
        self.g8.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.g8.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/white_knight.png);")
        self.g8.setIcon(self.icon_Bknight_w)
        self.g8.setIconSize(QtCore.QSize(65, 65))
        self.g8.setText("")
        self.g8.setCheckable(True)
        self.g8.setAutoExclusive(True)
        self.g8.setObjectName("g8")
        self.gridLayout.addWidget(self.g8, 7, 1, 1, 1)
        self.f8 = QtWidgets.QPushButton(Chessboard)
        self.f8.setMinimumSize(QtCore.QSize(70, 70))
        self.f8.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.f8.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/white_bishop.png);")
        self.f8.setIcon(self.icon_Bbishop_b)
        self.f8.setIconSize(QtCore.QSize(65, 65))
        self.f8.setText("")
        self.f8.setCheckable(True)
        self.f8.setAutoExclusive(True)
        self.f8.setObjectName("f8")
        self.gridLayout.addWidget(self.f8, 7, 2, 1, 1)
        self.e8 = QtWidgets.QPushButton(Chessboard)
        self.e8.setMinimumSize(QtCore.QSize(70, 70))
        self.e8.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.e8.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/white_queen.png);")
        self.e8.setIcon(self.icon_Bking_w)
        self.e8.setIconSize(QtCore.QSize(65, 65))
        self.e8.setText("")
        self.e8.setCheckable(True)
        self.e8.setAutoExclusive(True)
        self.e8.setObjectName("e8")
        self.gridLayout.addWidget(self.e8, 7, 3, 1, 1)
        self.d8 = QtWidgets.QPushButton(Chessboard)
        self.d8.setMinimumSize(QtCore.QSize(70, 70))
        self.d8.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.d8.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/white_king.png);")
        self.d8.setIcon(self.icon_Bqueen_b)
        self.d8.setIconSize(QtCore.QSize(65, 65))
        self.d8.setText("")
        self.d8.setCheckable(True)
        self.d8.setAutoExclusive(True)
        self.d8.setObjectName("d8")
        self.gridLayout.addWidget(self.d8, 7, 6, 1, 1)
        self.c8 = QtWidgets.QPushButton(Chessboard)
        self.c8.setMinimumSize(QtCore.QSize(70, 70))
        self.c8.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.c8.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/white_bishop.png);")
        self.c8.setIcon(self.icon_Bbishop_w)
        self.c8.setIconSize(QtCore.QSize(65, 65))
        self.c8.setText("")
        self.c8.setCheckable(True)
        self.c8.setAutoExclusive(True)
        self.c8.setObjectName("c8")
        self.gridLayout.addWidget(self.c8, 7, 7, 1, 1)
        self.b8 = QtWidgets.QPushButton(Chessboard)
        self.b8.setMinimumSize(QtCore.QSize(70, 70))
        self.b8.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.b8.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/white_knight.png);")
        self.b8.setIcon(self.icon_Bknight_b)
        self.b8.setIconSize(QtCore.QSize(65, 65))
        self.b8.setText("")
        self.b8.setCheckable(True)
        self.b8.setAutoExclusive(True)
        self.b8.setObjectName("b8")
        self.gridLayout.addWidget(self.b8, 7, 8, 1, 1)
        self.a8 = QtWidgets.QPushButton(Chessboard)
        self.a8.setMinimumSize(QtCore.QSize(70, 70))
        self.a8.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.a8.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/white_rook.png);")
        self.a8.setIcon(self.icon_Brook_w)
        self.a8.setIconSize(QtCore.QSize(65, 65))
        self.a8.setText("")
        self.a8.setCheckable(True)
        self.a8.setAutoExclusive(True)
        self.a8.setObjectName("a8")
        self.gridLayout.addWidget(self.a8, 7, 9, 1, 1)
        self.h7 = QtWidgets.QPushButton(Chessboard)
        self.h7.setMinimumSize(QtCore.QSize(70, 70))
        self.h7.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.h7.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/white_pawn.png);")
        self.h7.setIcon(self.icon_Bpawn_w)
        self.h7.setIconSize(QtCore.QSize(65, 65))
        self.h7.setText("")
        self.h7.setAutoExclusive(True)
        self.h7.setObjectName("h7")
        self.gridLayout.addWidget(self.h7, 6, 0, 1, 1)
        self.g7 = QtWidgets.QPushButton(Chessboard)
        self.g7.setMinimumSize(QtCore.QSize(70, 70))
        self.g7.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.g7.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/white_pawn.png);")
        self.g7.setIcon(self.icon_Bpawn_b)
        self.g7.setIconSize(QtCore.QSize(65, 65))
        self.g7.setText("")
        self.g7.setCheckable(True)
        self.g7.setAutoExclusive(True)
        self.g7.setObjectName("g7")
        self.gridLayout.addWidget(self.g7, 6, 1, 1, 1)
        self.f7 = QtWidgets.QPushButton(Chessboard)
        self.f7.setMinimumSize(QtCore.QSize(70, 70))
        self.f7.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.f7.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/white_pawn.png);")
        self.f7.setIcon(self.icon_Bpawn_w)
        self.f7.setIconSize(QtCore.QSize(65, 65))
        self.f7.setText("")
        self.f7.setCheckable(True)
        self.f7.setAutoExclusive(True)
        self.f7.setObjectName("f7")
        self.gridLayout.addWidget(self.f7, 6, 2, 1, 1)
        self.e7 = QtWidgets.QPushButton(Chessboard)
        self.e7.setMinimumSize(QtCore.QSize(70, 70))
        self.e7.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.e7.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/white_pawn.png);")
        self.e7.setIcon(self.icon_Bpawn_b)
        self.e7.setIconSize(QtCore.QSize(65, 65))
        self.e7.setText("")
        self.e7.setCheckable(True)
        self.e7.setAutoExclusive(True)
        self.e7.setObjectName("e7")
        self.gridLayout.addWidget(self.e7, 6, 3, 1, 1)
        self.d7 = QtWidgets.QPushButton(Chessboard)
        self.d7.setMinimumSize(QtCore.QSize(70, 70))
        self.d7.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.d7.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/white_pawn.png);")
        self.d7.setIcon(self.icon_Bpawn_w)
        self.d7.setIconSize(QtCore.QSize(65, 65))
        self.d7.setText("")
        self.d7.setCheckable(True)
        self.d7.setAutoExclusive(True)
        self.d7.setObjectName("d7")
        self.gridLayout.addWidget(self.d7, 6, 6, 1, 1)
        self.c7 = QtWidgets.QPushButton(Chessboard)
        self.c7.setMinimumSize(QtCore.QSize(70, 70))
        self.c7.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.c7.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/white_pawn.png);")
        self.c7.setIcon(self.icon_Bpawn_b)
        self.c7.setIconSize(QtCore.QSize(65, 65))
        self.c7.setText("")
        self.c7.setCheckable(True)
        self.c7.setAutoExclusive(True)
        self.c7.setObjectName("c7")
        self.gridLayout.addWidget(self.c7, 6, 7, 1, 1)
        self.b7 = QtWidgets.QPushButton(Chessboard)
        self.b7.setMinimumSize(QtCore.QSize(70, 70))
        self.b7.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.b7.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/white_pawn.png);")
        self.b7.setIcon(self.icon_Bpawn_w)
        self.b7.setIconSize(QtCore.QSize(65, 65))
        self.b7.setText("")
        self.b7.setCheckable(True)
        self.b7.setAutoExclusive(True)
        self.b7.setObjectName("b7")
        self.gridLayout.addWidget(self.b7, 6, 8, 1, 1)
        self.a7 = QtWidgets.QPushButton(Chessboard)
        self.a7.setMinimumSize(QtCore.QSize(70, 70))
        self.a7.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.a7.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/white_pawn.png);")
        self.a7.setIcon(self.icon_Bpawn_b)
        self.a7.setIconSize(QtCore.QSize(65, 65))
        self.a7.setText("")
        self.a7.setCheckable(True)
        self.a7.setAutoExclusive(True)
        self.a7.setObjectName("a7")
        self.gridLayout.addWidget(self.a7, 6, 9, 1, 1)
        self.h6 = QtWidgets.QPushButton(Chessboard)
        self.h6.setMinimumSize(QtCore.QSize(70, 70))
        self.h6.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.h6.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.h6.setIcon(self.icon_grey)
        self.h6.setIconSize(QSize(65, 65))
        self.h6.setText("")
        self.h6.setCheckable(True)
        self.h6.setAutoExclusive(True)
        self.h6.setObjectName("h6")
        self.gridLayout.addWidget(self.h6, 5, 0, 1, 1)
        self.g6 = QtWidgets.QPushButton(Chessboard)
        self.g6.setMinimumSize(QtCore.QSize(70, 70))
        self.g6.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.g6.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.g6.setIcon(QtGui.QIcon())
        self.g6.setIconSize(QtCore.QSize(65, 65))
        self.g6.setText("")
        self.g6.setCheckable(True)
        self.g6.setAutoExclusive(True)
        self.g6.setObjectName("g6")
        self.gridLayout.addWidget(self.g6, 5, 1, 1, 1)
        self.f6 = QtWidgets.QPushButton(Chessboard)
        self.f6.setMinimumSize(QtCore.QSize(70, 70))
        self.f6.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.f6.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.f6.setIcon(self.icon_grey)
        self.f6.setIconSize(QtCore.QSize(65, 65))
        self.f6.setText("")
        self.f6.setCheckable(True)
        self.f6.setAutoExclusive(True)
        self.f6.setObjectName("f6")
        self.gridLayout.addWidget(self.f6, 5, 2, 1, 1)
        self.e6 = QtWidgets.QPushButton(Chessboard)
        self.e6.setMinimumSize(QtCore.QSize(70, 70))
        self.e6.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.e6.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.e6.setIcon(QtGui.QIcon())
        self.e6.setIconSize(QtCore.QSize(65, 65))
        self.e6.setText("")
        self.e6.setCheckable(True)
        self.e6.setAutoExclusive(True)
        self.e6.setObjectName("e6")
        self.gridLayout.addWidget(self.e6, 5, 3, 1, 1)
        self.d6 = QtWidgets.QPushButton(Chessboard)
        self.d6.setMinimumSize(QtCore.QSize(70, 70))
        self.d6.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.d6.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.d6.setIcon(self.icon_grey)
        self.d6.setIconSize(QtCore.QSize(65, 65))
        self.d6.setText("")
        self.d6.setCheckable(True)
        self.d6.setAutoExclusive(True)
        self.d6.setObjectName("d6")
        self.gridLayout.addWidget(self.d6, 5, 6, 1, 1)
        self.c6 = QtWidgets.QPushButton(Chessboard)
        self.c6.setMinimumSize(QtCore.QSize(70, 70))
        self.c6.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.c6.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.c6.setIcon(QtGui.QIcon())
        self.c6.setIconSize(QtCore.QSize(65, 65))
        self.c6.setText("")
        self.c6.setCheckable(True)
        self.c6.setAutoExclusive(True)
        self.c6.setObjectName("c6")
        self.gridLayout.addWidget(self.c6, 5, 7, 1, 1)
        self.b6 = QtWidgets.QPushButton(Chessboard)
        self.b6.setMinimumSize(QtCore.QSize(70, 70))
        self.b6.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.b6.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.b6.setIcon(self.icon_grey)
        self.b6.setIconSize(QtCore.QSize(65, 65))
        self.b6.setText("")
        self.b6.setCheckable(True)
        self.b6.setAutoExclusive(True)
        self.b6.setObjectName("b6")
        self.gridLayout.addWidget(self.b6, 5, 8, 1, 1)
        self.a6 = QtWidgets.QPushButton(Chessboard)
        self.a6.setMinimumSize(QtCore.QSize(70, 70))
        self.a6.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.a6.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.a6.setIcon(QtGui.QIcon())
        self.a6.setIconSize(QtCore.QSize(65, 65))
        self.a6.setText("")
        self.a6.setCheckable(True)
        self.a6.setAutoExclusive(True)
        self.a6.setObjectName("a6")
        self.gridLayout.addWidget(self.a6, 5, 9, 1, 1)
        self.h5 = QtWidgets.QPushButton(Chessboard)
        self.h5.setMinimumSize(QtCore.QSize(70, 70))
        self.h5.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.h5.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.h5.setIcon(QtGui.QIcon())
        self.h5.setIconSize(QtCore.QSize(65, 65))
        self.h5.setText("")
        self.h5.setCheckable(True)
        self.h5.setAutoExclusive(True)
        self.h5.setObjectName("h5")
        self.gridLayout.addWidget(self.h5, 4, 0, 1, 1)
        self.g5 = QtWidgets.QPushButton(Chessboard)
        self.g5.setMinimumSize(QtCore.QSize(70, 70))
        self.g5.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.g5.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.g5.setIcon(self.icon_grey)
        self.g5.setIconSize(QtCore.QSize(65, 65))
        self.g5.setText("")
        self.g5.setCheckable(True)
        self.g5.setAutoExclusive(True)
        self.g5.setObjectName("g5")
        self.gridLayout.addWidget(self.g5, 4, 1, 1, 1)
        self.f5 = QtWidgets.QPushButton(Chessboard)
        self.f5.setMinimumSize(QtCore.QSize(70, 70))
        self.f5.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.f5.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.f5.setIcon(QtGui.QIcon())
        self.f5.setIconSize(QtCore.QSize(65, 65))
        self.f5.setText("")
        self.f5.setCheckable(True)
        self.f5.setAutoExclusive(True)
        self.f5.setObjectName("f5")
        self.gridLayout.addWidget(self.f5, 4, 2, 1, 1)
        self.e5 = QtWidgets.QPushButton(Chessboard)
        self.e5.setMinimumSize(QtCore.QSize(70, 70))
        self.e5.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.e5.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.e5.setIcon(self.icon_grey)
        self.e5.setIconSize(QtCore.QSize(65, 65))
        self.e5.setText("")
        self.e5.setCheckable(True)
        self.e5.setAutoExclusive(True)
        self.e5.setObjectName("e5")
        self.gridLayout.addWidget(self.e5, 4, 3, 1, 1)
        self.d5 = QtWidgets.QPushButton(Chessboard)
        self.d5.setMinimumSize(QtCore.QSize(70, 70))
        self.d5.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.d5.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.d5.setIcon(QtGui.QIcon())
        self.d5.setIconSize(QtCore.QSize(65, 65))
        self.d5.setText("")
        self.d5.setCheckable(True)
        self.d5.setAutoExclusive(True)
        self.d5.setObjectName("d5")
        self.gridLayout.addWidget(self.d5, 4, 6, 1, 1)
        self.c5 = QtWidgets.QPushButton(Chessboard)
        self.c5.setMinimumSize(QtCore.QSize(70, 70))
        self.c5.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.c5.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.c5.setIcon(self.icon_grey)
        self.c5.setIconSize(QtCore.QSize(65, 65))
        self.c5.setText("")
        self.c5.setCheckable(True)
        self.c5.setAutoExclusive(True)
        self.c5.setObjectName("c5")
        self.gridLayout.addWidget(self.c5, 4, 7, 1, 1)
        self.b5 = QtWidgets.QPushButton(Chessboard)
        self.b5.setMinimumSize(QtCore.QSize(70, 70))
        self.b5.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.b5.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.b5.setIcon(QtGui.QIcon())
        self.b5.setIconSize(QtCore.QSize(65, 65))
        self.b5.setText("")
        self.b5.setCheckable(True)
        self.b5.setAutoExclusive(True)
        self.b5.setChecked(False)
        self.b5.setObjectName("b5")
        self.gridLayout.addWidget(self.b5, 4, 8, 1, 1)
        self.a5 = QtWidgets.QPushButton(Chessboard)
        self.a5.setMinimumSize(QtCore.QSize(70, 70))
        self.a5.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.a5.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.a5.setIcon(self.icon_grey)
        self.a5.setIconSize(QtCore.QSize(65, 65))
        self.a5.setText("")
        self.a5.setCheckable(True)
        self.a5.setAutoExclusive(True)
        self.a5.setAutoDefault(False)
        self.a5.setObjectName("a5")
        self.gridLayout.addWidget(self.a5, 4, 9, 1, 1)
        self.h4 = QtWidgets.QPushButton(Chessboard)
        self.h4.setMinimumSize(QtCore.QSize(70, 70))
        self.h4.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.h4.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.h4.setIcon(self.icon_grey)
        self.h4.setIconSize(QtCore.QSize(65, 65))
        self.h4.setText("")
        self.h4.setCheckable(True)
        self.h4.setAutoExclusive(True)
        self.h4.setObjectName("h4")
        self.gridLayout.addWidget(self.h4, 3, 0, 1, 1)
        self.g4 = QtWidgets.QPushButton(Chessboard)
        self.g4.setMinimumSize(QtCore.QSize(70, 70))
        self.g4.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.g4.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.g4.setIcon(QtGui.QIcon())
        self.g4.setIconSize(QtCore.QSize(65, 65))
        self.g4.setText("")
        self.g4.setCheckable(True)
        self.g4.setAutoExclusive(True)
        self.g4.setObjectName("g4")
        self.gridLayout.addWidget(self.g4, 3, 1, 1, 1)
        self.f4 = QtWidgets.QPushButton(Chessboard)
        self.f4.setMinimumSize(QtCore.QSize(70, 70))
        self.f4.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.f4.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.f4.setIcon(self.icon_grey)
        self.f4.setIconSize(QtCore.QSize(65, 65))
        self.f4.setText("")
        self.f4.setCheckable(True)
        self.f4.setAutoExclusive(True)
        self.f4.setObjectName("f4")
        self.gridLayout.addWidget(self.f4, 3, 2, 1, 1)
        self.e4 = QtWidgets.QPushButton(Chessboard)
        self.e4.setMinimumSize(QtCore.QSize(70, 70))
        self.e4.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.e4.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.e4.setIcon(QtGui.QIcon())
        self.e4.setIconSize(QtCore.QSize(65, 65))
        self.e4.setText("")
        self.e4.setCheckable(True)
        self.e4.setAutoExclusive(True)
        self.e4.setObjectName("e4")
        self.gridLayout.addWidget(self.e4, 3, 3, 1, 1)
        self.d4 = QtWidgets.QPushButton(Chessboard)
        self.d4.setMinimumSize(QtCore.QSize(70, 70))
        self.d4.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.d4.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.d4.setIcon(self.icon_grey)
        self.d4.setIconSize(QtCore.QSize(65, 65))
        self.d4.setText("")
        self.d4.setCheckable(True)
        self.d4.setAutoExclusive(True)
        self.d4.setObjectName("d4")
        self.gridLayout.addWidget(self.d4, 3, 6, 1, 1)
        self.c4 = QtWidgets.QPushButton(Chessboard)
        self.c4.setMinimumSize(QtCore.QSize(70, 70))
        self.c4.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.c4.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.c4.setIcon(QtGui.QIcon())
        self.c4.setIconSize(QtCore.QSize(65, 65))
        self.c4.setText("")
        self.c4.setCheckable(True)
        self.c4.setAutoExclusive(True)
        self.c4.setObjectName("c4")
        self.gridLayout.addWidget(self.c4, 3, 7, 1, 1)
        self.b4 = QtWidgets.QPushButton(Chessboard)
        self.b4.setMinimumSize(QtCore.QSize(70, 70))
        self.b4.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.b4.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.b4.setIcon(self.icon_grey)
        self.b4.setIconSize(QtCore.QSize(65, 65))
        self.b4.setText("")
        self.b4.setCheckable(True)
        self.b4.setAutoExclusive(True)
        self.b4.setObjectName("b4")
        self.gridLayout.addWidget(self.b4, 3, 8, 1, 1)
        self.a4 = QtWidgets.QPushButton(Chessboard)
        self.a4.setMinimumSize(QtCore.QSize(70, 70))
        self.a4.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.a4.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.a4.setIcon(QtGui.QIcon())
        self.a4.setIconSize(QtCore.QSize(65, 65))
        self.a4.setText("")
        self.a4.setCheckable(True)
        self.a4.setAutoExclusive(True)
        self.a4.setObjectName("a4")
        self.gridLayout.addWidget(self.a4, 3, 9, 1, 1)
        self.h3 = QtWidgets.QPushButton(Chessboard)
        self.h3.setMinimumSize(QtCore.QSize(70, 70))
        self.h3.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.h3.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.h3.setIcon(QtGui.QIcon())
        self.h3.setIconSize(QtCore.QSize(65, 65))
        self.h3.setText("")
        self.h3.setCheckable(True)
        self.h3.setAutoExclusive(True)
        self.h3.setObjectName("h3")
        self.gridLayout.addWidget(self.h3, 2, 0, 1, 1)
        self.g3 = QtWidgets.QPushButton(Chessboard)
        self.g3.setMinimumSize(QtCore.QSize(70, 70))
        self.g3.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.g3.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.g3.setIcon(self.icon_grey)
        self.g3.setIconSize(QtCore.QSize(65, 65))
        self.g3.setText("")
        self.g3.setCheckable(True)
        self.g3.setAutoExclusive(True)
        self.g3.setObjectName("g3")
        self.gridLayout.addWidget(self.g3, 2, 1, 1, 1)
        self.f3 = QtWidgets.QPushButton(Chessboard)
        self.f3.setMinimumSize(QtCore.QSize(70, 70))
        self.f3.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.f3.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.f3.setIcon(QtGui.QIcon())
        self.f3.setIconSize(QtCore.QSize(65, 65))
        self.f3.setText("")
        self.f3.setCheckable(True)
        self.f3.setAutoExclusive(True)
        self.f3.setObjectName("f3")
        self.gridLayout.addWidget(self.f3, 2, 2, 1, 1)
        self.e3 = QtWidgets.QPushButton(Chessboard)
        self.e3.setMinimumSize(QtCore.QSize(70, 70))
        self.e3.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.e3.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.e3.setIcon(self.icon_grey)
        self.e3.setIconSize(QtCore.QSize(65, 65))
        self.e3.setText("")
        self.e3.setCheckable(True)
        self.e3.setAutoExclusive(True)
        self.e3.setObjectName("e3")
        self.gridLayout.addWidget(self.e3, 2, 3, 1, 1)
        self.d3 = QtWidgets.QPushButton(Chessboard)
        self.d3.setMinimumSize(QtCore.QSize(70, 70))
        self.d3.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.d3.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.d3.setIcon(QtGui.QIcon())
        self.d3.setIconSize(QtCore.QSize(65, 65))
        self.d3.setText("")
        self.d3.setCheckable(True)
        self.d3.setAutoExclusive(True)
        self.d3.setObjectName("d3")
        self.gridLayout.addWidget(self.d3, 2, 6, 1, 1)
        self.c3 = QtWidgets.QPushButton(Chessboard)
        self.c3.setMinimumSize(QtCore.QSize(70, 70))
        self.c3.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.c3.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.c3.setIcon(self.icon_grey)
        self.c3.setIconSize(QtCore.QSize(65, 65))
        self.c3.setText("")
        self.c3.setCheckable(True)
        self.c3.setAutoExclusive(True)
        self.c3.setObjectName("c3")
        self.gridLayout.addWidget(self.c3, 2, 7, 1, 1)
        self.b3 = QtWidgets.QPushButton(Chessboard)
        self.b3.setMinimumSize(QtCore.QSize(70, 70))
        self.b3.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.b3.setStyleSheet("background-image: url(:/images/images/white.jpeg);")
        self.b3.setIcon(QtGui.QIcon())
        self.b3.setIconSize(QtCore.QSize(65, 65))
        self.b3.setText("")
        self.b3.setCheckable(True)
        self.b3.setAutoExclusive(True)
        self.b3.setObjectName("b3")
        self.gridLayout.addWidget(self.b3, 2, 8, 1, 1)
        self.a3 = QtWidgets.QPushButton(Chessboard)
        self.a3.setMinimumSize(QtCore.QSize(70, 70))
        self.a3.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.a3.setStyleSheet("background-image: url(:/images/images/grey.jpg);")
        self.a3.setIcon(self.icon_grey)
        self.a3.setIconSize(QtCore.QSize(65, 65))
        self.a3.setText("")
        self.a3.setCheckable(True)
        self.a3.setAutoExclusive(True)
        self.a3.setObjectName("a3")
        self.gridLayout.addWidget(self.a3, 2, 9, 1, 1)
        self.h2 = QtWidgets.QPushButton(Chessboard)
        self.h2.setMinimumSize(QtCore.QSize(70, 70))
        self.h2.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.h2.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/black_pawn.png);")
        self.h2.setIcon(self.icon_Wpawn_b)
        self.h2.setIconSize(QtCore.QSize(65, 65))
        self.h2.setText("")
        self.h2.setCheckable(True)
        self.h2.setAutoExclusive(True)
        self.h2.setObjectName("h2")
        self.gridLayout.addWidget(self.h2, 1, 0, 1, 1)
        self.g2 = QtWidgets.QPushButton(Chessboard)
        self.g2.setMinimumSize(QtCore.QSize(70, 70))
        self.g2.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.g2.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/black_pawn.png);")
        self.g2.setIcon(self.icon_Wpawn_w)
        self.g2.setIconSize(QtCore.QSize(65, 65))
        self.g2.setText("")
        self.g2.setCheckable(True)
        self.g2.setAutoExclusive(True)
        self.g2.setObjectName("g2")
        self.gridLayout.addWidget(self.g2, 1, 1, 1, 1)
        self.f2 = QtWidgets.QPushButton(Chessboard)
        self.f2.setMinimumSize(QtCore.QSize(70, 70))
        self.f2.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.f2.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/black_pawn.png);")
        self.f2.setIcon(self.icon_Wpawn_b)
        self.f2.setIconSize(QtCore.QSize(65, 65))
        self.f2.setText("")
        self.f2.setCheckable(True)
        self.f2.setAutoExclusive(True)
        self.f2.setObjectName("f2")
        self.gridLayout.addWidget(self.f2, 1, 2, 1, 1)
        self.e2 = QtWidgets.QPushButton(Chessboard)
        self.e2.setMinimumSize(QtCore.QSize(70, 70))
        self.e2.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.e2.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/black_pawn.png);")
        self.e2.setIcon(self.icon_Wpawn_w)
        self.e2.setIconSize(QtCore.QSize(65, 65))
        self.e2.setText("")
        self.e2.setCheckable(True)
        self.e2.setAutoExclusive(True)
        self.e2.setObjectName("e2")
        self.gridLayout.addWidget(self.e2, 1, 3, 1, 1)
        self.d2 = QtWidgets.QPushButton(Chessboard)
        self.d2.setMinimumSize(QtCore.QSize(70, 70))
        self.d2.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.d2.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/black_pawn.png);")
        self.d2.setIcon(self.icon_Wpawn_b)
        self.d2.setIconSize(QtCore.QSize(65, 65))
        self.d2.setText("")
        self.d2.setCheckable(True)
        self.d2.setAutoExclusive(True)
        self.d2.setObjectName("d2")
        self.gridLayout.addWidget(self.d2, 1, 6, 1, 1)
        self.c2 = QtWidgets.QPushButton(Chessboard)
        self.c2.setMinimumSize(QtCore.QSize(70, 70))
        self.c2.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.c2.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/black_pawn.png);")
        self.c2.setIcon(self.icon_Wpawn_w)
        self.c2.setIconSize(QtCore.QSize(65, 65))
        self.c2.setText("")
        self.c2.setCheckable(True)
        self.c2.setAutoExclusive(True)
        self.c2.setObjectName("c2")
        self.gridLayout.addWidget(self.c2, 1, 7, 1, 1)
        self.b2 = QtWidgets.QPushButton(Chessboard)
        self.b2.setMinimumSize(QtCore.QSize(70, 70))
        self.b2.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.b2.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/black_pawn.png);")
        self.b2.setIcon(self.icon_Wpawn_b)
        self.b2.setIconSize(QtCore.QSize(65, 65))
        self.b2.setText("")
        self.b2.setCheckable(True)
        self.b2.setAutoExclusive(True)
        self.b2.setObjectName("b2")
        self.gridLayout.addWidget(self.b2, 1, 8, 1, 1)
        self.a2 = QtWidgets.QPushButton(Chessboard)
        self.a2.setMinimumSize(QtCore.QSize(70, 70))
        self.a2.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.a2.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/black_pawn.png);")
        self.a2.setIcon(self.icon_Wpawn_w)
        self.a2.setIconSize(QtCore.QSize(65, 65))
        self.a2.setText("")
        self.a2.setCheckable(True)
        self.a2.setAutoExclusive(True)
        self.a2.setObjectName("a2")
        self.gridLayout.addWidget(self.a2, 1, 9, 1, 1)
        self.h1 = QtWidgets.QPushButton(Chessboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h1.sizePolicy().hasHeightForWidth())
        self.h1.setSizePolicy(sizePolicy)
        self.h1.setMinimumSize(QtCore.QSize(70, 70))
        self.h1.setMaximumSize(QtCore.QSize(70, 100))
        #self.h1.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/black_rook.png);") #url(:/images/images/white.jpeg)
        self.h1.setIcon(self.icon_Wrook_w)
        self.h1.setIconSize(QtCore.QSize(65, 65))
        self.h1.setText("")
        self.h1.setCheckable(True)
        self.h1.setAutoExclusive(True)
        self.h1.setAutoRepeat(False)
        self.h1.setObjectName("h1")
        self.gridLayout.addWidget(self.h1, 0, 0, 1, 1)
        self.g1 = QtWidgets.QPushButton(Chessboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g1.sizePolicy().hasHeightForWidth())
        self.g1.setSizePolicy(sizePolicy)
        self.g1.setMinimumSize(QtCore.QSize(70, 70))
        self.g1.setMaximumSize(QtCore.QSize(70, 100))
        #self.g1.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/black_knight.png);")
        self.g1.setIcon(self.icon_Wknight_b)
        self.g1.setIconSize(QtCore.QSize(65, 65))
        self.g1.setText("")
        self.g1.setCheckable(True)
        self.g1.setAutoExclusive(True)
        self.g1.setObjectName("g1")
        self.gridLayout.addWidget(self.g1, 0, 1, 1, 1)
        self.f1 = QtWidgets.QPushButton(Chessboard)
        self.f1.setMinimumSize(QtCore.QSize(70, 70))
        self.f1.setMaximumSize(QtCore.QSize(70, 100))
        #self.f1.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/black_bishop.png);")
        self.f1.setIcon(self.icon_Wbishop_w)
        self.f1.setIconSize(QtCore.QSize(65, 65))
        self.f1.setText("")
        self.f1.setCheckable(True)
        self.f1.setAutoExclusive(True)
        self.f1.setObjectName("f1")
        self.gridLayout.addWidget(self.f1, 0, 2, 1, 1)
        self.e1 = QtWidgets.QPushButton(Chessboard)
        self.e1.setMinimumSize(QtCore.QSize(70, 70))
        self.e1.setMaximumSize(QtCore.QSize(70, 100))
        #self.e1.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/black_queen.png);")
        self.e1.setIcon(self.icon_Wking_b)
        self.e1.setIconSize(QtCore.QSize(65, 65))
        self.e1.setText("")
        self.e1.setCheckable(True)
        self.e1.setAutoExclusive(True)
        self.e1.setObjectName("e1")
        self.gridLayout.addWidget(self.e1, 0, 3, 1, 1)
        self.d1 = QtWidgets.QPushButton(Chessboard)
        self.d1.setMinimumSize(QtCore.QSize(70, 70))
        self.d1.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.d1.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/black_king.png);")
        self.d1.setIcon(self.icon_Wqueen_w)
        self.d1.setIconSize(QtCore.QSize(65, 65))
        self.d1.setText("")
        self.d1.setCheckable(True)
        self.d1.setAutoExclusive(True)
        self.d1.setObjectName("d1")
        self.gridLayout.addWidget(self.d1, 0, 6, 1, 1)
        self.c1 = QtWidgets.QPushButton(Chessboard)
        self.c1.setMinimumSize(QtCore.QSize(70, 70))
        self.c1.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.c1.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/black_bishop.png);")
        self.c1.setIcon(self.icon_Wbishop_b)
        self.c1.setIconSize(QtCore.QSize(65, 65))
        self.c1.setText("")
        self.c1.setCheckable(True)
        self.c1.setAutoExclusive(True)
        self.c1.setObjectName("c1")
        self.gridLayout.addWidget(self.c1, 0, 7, 1, 1)
        self.b1 = QtWidgets.QPushButton(Chessboard)
        self.b1.setMinimumSize(QtCore.QSize(70, 70))
        self.b1.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.b1.setStyleSheet("background-image: url(:/images/images/white.jpeg);\n" "image: url(:/images/images/black_knight.png);")
        self.b1.setIcon(self.icon_Wknight_w)
        self.b1.setIconSize(QtCore.QSize(65, 65))
        self.b1.setText("")
        self.b1.setCheckable(True)
        self.b1.setAutoExclusive(True)
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 0, 8, 1, 1)
        self.a1 = QtWidgets.QPushButton(Chessboard)
        self.a1.setMinimumSize(QtCore.QSize(70, 70))
        self.a1.setMaximumSize(QtCore.QSize(70, 16777215))
        #self.a1.setStyleSheet("background-image: url(:/images/images/grey.jpg);\n" "image: url(:/images/images/black_rook.png);")
        self.a1.setIcon(self.icon_Wrook_b)
        self.a1.setIconSize(QtCore.QSize(65, 65))
        self.a1.setText("")
        self.a1.setCheckable(True)
        self.a1.setAutoExclusive(True)
        self.a1.setObjectName("a1")
        self.gridLayout.addWidget(self.a1, 0, 9, 1, 1)
        self.PlayGameModePushbutton = QtWidgets.QPushButton(Chessboard)
        self.PlayGameModePushbutton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlayGameModePushbutton.sizePolicy().hasHeightForWidth())
        self.PlayGameModePushbutton.setSizePolicy(sizePolicy)
        self.PlayGameModePushbutton.setMinimumSize(QtCore.QSize(70, 70))
        self.PlayGameModePushbutton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.PlayGameModePushbutton.setObjectName("PlayGameModePushbutton")
        self.gridLayout.addWidget(self.PlayGameModePushbutton, 6, 11, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.ManualModePushbutton = QtWidgets.QPushButton(Chessboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManualModePushbutton.sizePolicy().hasHeightForWidth())
        self.ManualModePushbutton.setSizePolicy(sizePolicy)
        self.ManualModePushbutton.setMinimumSize(QtCore.QSize(70, 70))
        self.ManualModePushbutton.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.ManualModePushbutton.setFont(font)
        self.ManualModePushbutton.setAcceptDrops(False)
        self.ManualModePushbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ManualModePushbutton.setAutoFillBackground(False)
        self.ManualModePushbutton.setCheckable(False)
        self.ManualModePushbutton.setChecked(False)
        self.ManualModePushbutton.setAutoRepeat(False)
        self.ManualModePushbutton.setAutoExclusive(False)
        self.ManualModePushbutton.setObjectName("ManualModePushbutton")
        self.gridLayout.addWidget(self.ManualModePushbutton, 7, 11, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.GLabel = QtWidgets.QLabel(Chessboard)
        self.GLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GLabel.setObjectName("GLabel")
        self.gridLayout.addWidget(self.GLabel, 8, 1, 1, 1)
        self.HLabel = QtWidgets.QLabel(Chessboard)
        self.HLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.HLabel.setObjectName("HLabel")
        self.gridLayout.addWidget(self.HLabel, 8, 0, 1, 1)
        self.DLabel = QtWidgets.QLabel(Chessboard)
        self.DLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DLabel.setObjectName("DLabel")
        self.gridLayout.addWidget(self.DLabel, 8, 6, 1, 1)
        self.CLabel = QtWidgets.QLabel(Chessboard)
        self.CLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CLabel.setObjectName("CLabel")
        self.gridLayout.addWidget(self.CLabel, 8, 7, 1, 1)
        self.BLabel = QtWidgets.QLabel(Chessboard)
        self.BLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BLabel.setObjectName("BLabel")
        self.gridLayout.addWidget(self.BLabel, 8, 8, 1, 1)
        self.Label3 = QtWidgets.QLabel(Chessboard)
        self.Label3.setAlignment(QtCore.Qt.AlignCenter)
        self.Label3.setObjectName("Label3")
        self.gridLayout.addWidget(self.Label3, 2, 10, 1, 1)
        self.Label1 = QtWidgets.QLabel(Chessboard)
        self.Label1.setAlignment(QtCore.Qt.AlignCenter)
        self.Label1.setObjectName("Label1")
        self.gridLayout.addWidget(self.Label1, 0, 10, 1, 1)
        self.ELabel = QtWidgets.QLabel(Chessboard)
        self.ELabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ELabel.setObjectName("ELabel")
        self.gridLayout.addWidget(self.ELabel, 8, 3, 1, 1)
        self.FLabel = QtWidgets.QLabel(Chessboard)
        self.FLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FLabel.setObjectName("FLabel")
        self.gridLayout.addWidget(self.FLabel, 8, 2, 1, 1)
        self.Label2 = QtWidgets.QLabel(Chessboard)
        self.Label2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label2.setObjectName("Label2")
        self.gridLayout.addWidget(self.Label2, 1, 10, 1, 1)
        self.Label7 = QtWidgets.QLabel(Chessboard)
        self.Label7.setAlignment(QtCore.Qt.AlignCenter)
        self.Label7.setObjectName("Label7")
        self.gridLayout.addWidget(self.Label7, 6, 10, 1, 1)
        self.ALabel = QtWidgets.QLabel(Chessboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HLabel.sizePolicy().hasHeightForWidth())
        self.ALabel.setSizePolicy(sizePolicy)
        self.ALabel.setMinimumSize(QtCore.QSize(0, 50))
        self.ALabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ALabel.setObjectName("ALabel")
        self.gridLayout.addWidget(self.ALabel, 8, 9, 1, 1)
        self.Label6 = QtWidgets.QLabel(Chessboard)
        self.Label6.setAlignment(QtCore.Qt.AlignCenter)
        self.Label6.setObjectName("Label6")
        self.gridLayout.addWidget(self.Label6, 5, 10, 1, 1)
        self.Label8 = QtWidgets.QLabel(Chessboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label1.sizePolicy().hasHeightForWidth())
        self.Label8.setSizePolicy(sizePolicy)
        self.Label8.setMinimumSize(QtCore.QSize(50, 0))
        self.Label8.setAlignment(QtCore.Qt.AlignCenter)
        self.Label8.setObjectName("Label8")
        self.gridLayout.addWidget(self.Label8, 7, 10, 1, 1)
        self.Label4 = QtWidgets.QLabel(Chessboard)
        self.Label4.setAlignment(QtCore.Qt.AlignCenter)
        self.Label4.setObjectName("Label4")
        self.gridLayout.addWidget(self.Label4, 3, 10, 1, 1)
        self.Label5 = QtWidgets.QLabel(Chessboard)
        self.Label5.setAlignment(QtCore.Qt.AlignCenter)
        self.Label5.setObjectName("Label5")
        self.gridLayout.addWidget(self.Label5, 4, 10, 1, 1)
        self.indicationLabel = QtWidgets.QLabel(Chessboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indicationLabel.sizePolicy().hasHeightForWidth())
        self.indicationLabel.setSizePolicy(sizePolicy)
        self.indicationLabel.setMinimumSize(QtCore.QSize(70, 70))
        self.indicationLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.indicationLabel.setFont(font)
        self.indicationLabel.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.indicationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.indicationLabel.setWordWrap(True)
        self.indicationLabel.setObjectName("indicationLabel")
        self.gridLayout.addWidget(self.indicationLabel, 0, 11, 1, 1)

        self.retranslateUi(Chessboard)
        QtCore.QMetaObject.connectSlotsByName(Chessboard)

        
    def retranslateUi(self, Chessboard):
        _translate = QtCore.QCoreApplication.translate
        Chessboard.setWindowTitle(_translate("Chessboard", "Chessboard"))
        self.BLabel.setText(_translate("Chessboard", "B"))
        self.ALabel.setText(_translate("Chessboard", "A"))
        self.ELabel.setText(_translate("Chessboard", "E"))
        self.FLabel.setText(_translate("Chessboard", "F"))
        self.GLabel.setText(_translate("Chessboard", "G"))
        self.Label6.setText(_translate("Chessboard", "6"))
        self.Label8.setText(_translate("Chessboard", "8"))
        self.DLabel.setText(_translate("Chessboard", "D"))
        self.CLabel.setText(_translate("Chessboard", "C"))
        self.Label7.setText(_translate("Chessboard", "7"))
        self.Label2.setText(_translate("Chessboard", "2"))
        self.HLabel.setText(_translate("Chessboard", "H"))
        self.Label3.setText(_translate("Chessboard", "3"))
        self.Label1.setText(_translate("Chessboard", "1"))
        self.Label5.setText(_translate("Chessboard", "5"))
        self.Label4.setText(_translate("Chessboard", "4"))
        self.PlayGameModePushbutton.setText(_translate("Chessboard", "Back to\n"
"game"))
        self.ManualModePushbutton.setText(_translate("Chessboard", "Manual\n"
"Mode"))
        self.indicationLabel.setText(_translate("Chessboard", "Waiting opponent move"))


if __name__ == "__main__":
    import sys
    app = MyApplication(sys.argv)  #Era QtWidgets.QApplication
    app_focus = app.focusWidget()
    Chessboard = QtWidgets.QWidget()
    ui = Ui_Chessboard_Black()
    ui.setupUi(Chessboard, app_focus)
    Chessboard.show()
    sys.exit(app.exec_())

