#!/usr/bin/env python
# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

GUI_PKG_DIR = '/home/luca/tiago_public_ws/src/chess_gui'

class Ui_InitializationWindow(object):
    def setupUi(self, InitializationWindow):
        InitializationWindow.setObjectName("InitializationWindow")
        InitializationWindow.resize(662, 505)
        self.centralwidget = QtWidgets.QWidget(InitializationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ChessboarPositioningLabel = QtWidgets.QLabel(self.centralwidget)
        self.ChessboarPositioningLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ChessboarPositioningLabel.setFont(font)
        self.ChessboarPositioningLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ChessboarPositioningLabel.setWordWrap(True)
        self.ChessboarPositioningLabel.setObjectName("ChessboarPositioningLabel")
        self.verticalLayout_2.addWidget(self.ChessboarPositioningLabel)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.GuidelineText = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GuidelineText.sizePolicy().hasHeightForWidth())
        self.GuidelineText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.GuidelineText.setFont(font)
        self.GuidelineText.setAlignment(QtCore.Qt.AlignCenter)
        self.GuidelineText.setWordWrap(True)
        self.GuidelineText.setIndent(-1)
        self.GuidelineText.setObjectName("GuidelineText")
        self.verticalLayout_2.addWidget(self.GuidelineText)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.CorrectPositioningImageLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CorrectPositioningImageLabel.sizePolicy().hasHeightForWidth())
        self.CorrectPositioningImageLabel.setSizePolicy(sizePolicy)
        self.CorrectPositioningImageLabel.setMinimumSize(QtCore.QSize(200, 250))
        self.CorrectPositioningImageLabel.setMaximumSize(QtCore.QSize(320, 250))
        self.CorrectPositioningImageLabel.setText("")
        self.CorrectPositioningImageLabel.setPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/correct_setup.png"))
        self.CorrectPositioningImageLabel.setScaledContents(True)
        self.CorrectPositioningImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CorrectPositioningImageLabel.setObjectName("CorrectPositioningImageLabel")
        self.gridLayout.addWidget(self.CorrectPositioningImageLabel, 0, 0, 1, 1)
        self.CurrentChessboardImageLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentChessboardImageLabel.sizePolicy().hasHeightForWidth())
        self.CurrentChessboardImageLabel.setSizePolicy(sizePolicy)
        self.CurrentChessboardImageLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.CurrentChessboardImageLabel.setMaximumSize(QtCore.QSize(50, 50))
        self.CurrentChessboardImageLabel.setText("")
        self.movie = QtGui.QMovie(GUI_PKG_DIR + "/images/ElaborationGif.gif")
        self.CurrentChessboardImageLabel.setMovie(self.movie)
        self.movie.start()
        #self.CurrentChessboardImageLabel.setPixmap(QtGui.QPixmap("images/Pulse-1s-211px.gif"))
        self.CurrentChessboardImageLabel.setScaledContents(True)
        self.CurrentChessboardImageLabel.setScaledContents(True)
        self.CurrentChessboardImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentChessboardImageLabel.setObjectName("CurrentChessboardImageLabel")
        self.gridLayout.addWidget(self.CurrentChessboardImageLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")       
        self.RepositionPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.RepositionPushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RepositionPushButton.sizePolicy().hasHeightForWidth())
        self.RepositionPushButton.setSizePolicy(sizePolicy)
        self.RepositionPushButton.setMinimumSize(QtCore.QSize(200, 50))
        self.RepositionPushButton.setMaximumSize(QtCore.QSize(500, 16777215))
        self.RepositionPushButton.setObjectName("RepositionPushButton")
        self.horizontalLayout.addWidget(self.RepositionPushButton)
        self.GoPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.GoPushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoPushButton.sizePolicy().hasHeightForWidth())
        self.GoPushButton.setSizePolicy(sizePolicy)
        self.GoPushButton.setMinimumSize(QtCore.QSize(200, 50))
        self.GoPushButton.setMaximumSize(QtCore.QSize(500, 16777215))
        self.GoPushButton.setMouseTracking(False)
        self.GoPushButton.setStyleSheet("")
        self.GoPushButton.setDefault(False)
        self.GoPushButton.setObjectName("GoPushButton")
        self.horizontalLayout.addWidget(self.GoPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        InitializationWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(InitializationWindow)
        self.statusbar.setObjectName("statusbar")
        InitializationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(InitializationWindow)
        QtCore.QMetaObject.connectSlotsByName(InitializationWindow)

    def retranslateUi(self, InitializationWindow):
        _translate = QtCore.QCoreApplication.translate
        InitializationWindow.setWindowTitle(_translate("InitializationWindow", "Initialization"))
        self.GuidelineText.setText(_translate("InitializationWindow", "Press the joystick button to start TIAGo\'s preparation\n(torso extension, looking down)."))
        self.ChessboarPositioningLabel.setText(_translate("InitializationWindow", "Position the chessboard in front of TIAGo and make sure that he sees it entirely (check positioning from the window below. If necessary, re-position and check again)."))
        self.label.setText(_translate("InitializationWindow", "Correct positioning sample"))
        self.label_2.setText(_translate("InitializationWindow", "Current positioning"))
        self.GoPushButton.setText(_translate("InitializationWindow", "Go to color choice"))
        self.RepositionPushButton.setText(_translate("InitializationWindow", "Re-position the chessboard"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InitializationWindow = QtWidgets.QMainWindow()
    ui = Ui_InitializationWindow()
    ui.setupUi(InitializationWindow)
    InitializationWindow.show()
    sys.exit(app.exec_())

