# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ManualModeWindow(object):
    def setupUi(self, ManualModeWindow):
        ManualModeWindow.setObjectName("ManualModeWindow")
        ManualModeWindow.resize(178, 474)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ManualModeWindow.sizePolicy().hasHeightForWidth())
        ManualModeWindow.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(ManualModeWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BlackKnightPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BlackKnightPushbutton.sizePolicy().hasHeightForWidth())
        self.BlackKnightPushbutton.setSizePolicy(sizePolicy)
        self.BlackKnightPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.BlackKnightPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.BlackKnightPushbutton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/B_Knight_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BlackKnightPushbutton.setIcon(icon)
        self.BlackKnightPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.BlackKnightPushbutton.setObjectName("BlackKnightPushbutton")
        self.gridLayout_2.addWidget(self.BlackKnightPushbutton, 1, 3, 1, 1)
        self.WhiteKnightPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhiteKnightPushbutton.sizePolicy().hasHeightForWidth())
        self.WhiteKnightPushbutton.setSizePolicy(sizePolicy)
        self.WhiteKnightPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.WhiteKnightPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.WhiteKnightPushbutton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/W_Knight_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WhiteKnightPushbutton.setIcon(icon1)
        self.WhiteKnightPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.WhiteKnightPushbutton.setObjectName("WhiteKnightPushbutton")
        self.gridLayout_2.addWidget(self.WhiteKnightPushbutton, 1, 0, 1, 1)
        self.BlackKingPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BlackKingPushbutton.sizePolicy().hasHeightForWidth())
        self.BlackKingPushbutton.setSizePolicy(sizePolicy)
        self.BlackKingPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.BlackKingPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.BlackKingPushbutton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/B_King_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BlackKingPushbutton.setIcon(icon2)
        self.BlackKingPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.BlackKingPushbutton.setObjectName("BlackKingPushbutton")
        self.gridLayout_2.addWidget(self.BlackKingPushbutton, 5, 3, 1, 1)
        self.BlackPawnPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BlackPawnPushbutton.sizePolicy().hasHeightForWidth())
        self.BlackPawnPushbutton.setSizePolicy(sizePolicy)
        self.BlackPawnPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.BlackPawnPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.BlackPawnPushbutton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/B_Pawn_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BlackPawnPushbutton.setIcon(icon3)
        self.BlackPawnPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.BlackPawnPushbutton.setObjectName("BlackPawnPushbutton")
        self.gridLayout_2.addWidget(self.BlackPawnPushbutton, 0, 3, 1, 1)
        self.WhiteBishopPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhiteBishopPushbutton.sizePolicy().hasHeightForWidth())
        self.WhiteBishopPushbutton.setSizePolicy(sizePolicy)
        self.WhiteBishopPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.WhiteBishopPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.WhiteBishopPushbutton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/W_Bishop_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WhiteBishopPushbutton.setIcon(icon4)
        self.WhiteBishopPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.WhiteBishopPushbutton.setObjectName("WhiteBishopPushbutton")
        self.gridLayout_2.addWidget(self.WhiteBishopPushbutton, 2, 0, 1, 1)
        self.BlackRookPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BlackRookPushbutton.sizePolicy().hasHeightForWidth())
        self.BlackRookPushbutton.setSizePolicy(sizePolicy)
        self.BlackRookPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.BlackRookPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.BlackRookPushbutton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/B_Rook_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BlackRookPushbutton.setIcon(icon5)
        self.BlackRookPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.BlackRookPushbutton.setObjectName("BlackRookPushbutton")
        self.gridLayout_2.addWidget(self.BlackRookPushbutton, 3, 3, 1, 1)
        self.WhiteRookPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhiteRookPushbutton.sizePolicy().hasHeightForWidth())
        self.WhiteRookPushbutton.setSizePolicy(sizePolicy)
        self.WhiteRookPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.WhiteRookPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.WhiteRookPushbutton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/W_Rook_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WhiteRookPushbutton.setIcon(icon6)
        self.WhiteRookPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.WhiteRookPushbutton.setObjectName("WhiteRookPushbutton")
        self.gridLayout_2.addWidget(self.WhiteRookPushbutton, 3, 0, 1, 1)
        self.WhiteKingPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhiteKingPushbutton.sizePolicy().hasHeightForWidth())
        self.WhiteKingPushbutton.setSizePolicy(sizePolicy)
        self.WhiteKingPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.WhiteKingPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.WhiteKingPushbutton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/W_King_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WhiteKingPushbutton.setIcon(icon7)
        self.WhiteKingPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.WhiteKingPushbutton.setObjectName("WhiteKingPushbutton")
        self.gridLayout_2.addWidget(self.WhiteKingPushbutton, 5, 0, 1, 1)
        self.BlackBishopPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BlackBishopPushbutton.sizePolicy().hasHeightForWidth())
        self.BlackBishopPushbutton.setSizePolicy(sizePolicy)
        self.BlackBishopPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.BlackBishopPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.BlackBishopPushbutton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/B_Bishop_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BlackBishopPushbutton.setIcon(icon8)
        self.BlackBishopPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.BlackBishopPushbutton.setObjectName("BlackBishopPushbutton")
        self.gridLayout_2.addWidget(self.BlackBishopPushbutton, 2, 3, 1, 1)
        self.WhitePawnPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhitePawnPushbutton.sizePolicy().hasHeightForWidth())
        self.WhitePawnPushbutton.setSizePolicy(sizePolicy)
        self.WhitePawnPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.WhitePawnPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.WhitePawnPushbutton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/W_Pawn_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WhitePawnPushbutton.setIcon(icon9)
        self.WhitePawnPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.WhitePawnPushbutton.setObjectName("WhitePawnPushbutton")
        self.gridLayout_2.addWidget(self.WhitePawnPushbutton, 0, 0, 1, 1)
        self.BlackQueenPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BlackQueenPushbutton.sizePolicy().hasHeightForWidth())
        self.BlackQueenPushbutton.setSizePolicy(sizePolicy)
        self.BlackQueenPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.BlackQueenPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.BlackQueenPushbutton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/B_Queen_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BlackQueenPushbutton.setIcon(icon10)
        self.BlackQueenPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.BlackQueenPushbutton.setObjectName("BlackQueenPushbutton")
        self.gridLayout_2.addWidget(self.BlackQueenPushbutton, 4, 3, 1, 1)
        self.WhiteQueenPushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhiteQueenPushbutton.sizePolicy().hasHeightForWidth())
        self.WhiteQueenPushbutton.setSizePolicy(sizePolicy)
        self.WhiteQueenPushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.WhiteQueenPushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.WhiteQueenPushbutton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../tiago_public_ws/src/chess_gui/images/W_Queen_w.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WhiteQueenPushbutton.setIcon(icon11)
        self.WhiteQueenPushbutton.setIconSize(QtCore.QSize(50, 50))
        self.WhiteQueenPushbutton.setObjectName("WhiteQueenPushbutton")
        self.gridLayout_2.addWidget(self.WhiteQueenPushbutton, 4, 0, 1, 1)
        self.EmptySquarePushbutton = QtWidgets.QPushButton(ManualModeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmptySquarePushbutton.sizePolicy().hasHeightForWidth())
        self.EmptySquarePushbutton.setSizePolicy(sizePolicy)
        self.EmptySquarePushbutton.setMinimumSize(QtCore.QSize(60, 60))
        self.EmptySquarePushbutton.setMaximumSize(QtCore.QSize(60, 60))
        self.EmptySquarePushbutton.setObjectName("EmptySquarePushbutton")
        self.gridLayout_2.addWidget(self.EmptySquarePushbutton, 6, 3, 1, 1)

        self.retranslateUi(ManualModeWindow)
        QtCore.QMetaObject.connectSlotsByName(ManualModeWindow)

    def retranslateUi(self, ManualModeWindow):
        _translate = QtCore.QCoreApplication.translate
        ManualModeWindow.setWindowTitle(_translate("ManualModeWindow", "Form"))
        self.EmptySquarePushbutton.setText(_translate("ManualModeWindow", "Empty\n"
"square"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManualModeWindow = QtWidgets.QWidget()
    ui = Ui_ManualModeWindow()
    ui.setupUi(ManualModeWindow)
    ManualModeWindow.show()
    sys.exit(app.exec_())

