# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

GUI_PKG_DIR = '/home/luca/tiago_public_ws/src/chess_gui'

class Ui_SearchConfirmationAskingWindow(object):
    def setupUi(self, SearchConfirmationAskingWindow):
        SearchConfirmationAskingWindow.setObjectName("SearchConfirmationAskingWindow")
        SearchConfirmationAskingWindow.resize(606, 577)
        self.verticalLayout = QtWidgets.QVBoxLayout(SearchConfirmationAskingWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horLayoutImage = QtWidgets.QHBoxLayout()
        self.horLayoutImage.setObjectName("horLayoutImage")
        self.ImageLabel = QtWidgets.QLabel(SearchConfirmationAskingWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageLabel.sizePolicy().hasHeightForWidth())
        self.ImageLabel.setSizePolicy(sizePolicy)
        self.ImageLabel.setMinimumSize(QtCore.QSize(0, 400))
        self.ImageLabel.setMaximumSize(QtCore.QSize(500, 400))
        self.ImageLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ImageLabel.setText("")
        self.ImageLabel.setPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/markers_localization.png"))
        self.ImageLabel.setScaledContents(True)
        self.ImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ImageLabel.setObjectName("ImageLabel")
        self.horLayoutImage.addWidget(self.ImageLabel)
        self.verticalLayout.addLayout(self.horLayoutImage)
        self.CompletionLabel = QtWidgets.QLabel(SearchConfirmationAskingWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CompletionLabel.sizePolicy().hasHeightForWidth())
        self.CompletionLabel.setSizePolicy(sizePolicy)
        self.CompletionLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CompletionLabel.setFont(font)
        self.CompletionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CompletionLabel.setObjectName("CompletionLabel")
        self.verticalLayout.addWidget(self.CompletionLabel)
        self.line = QtWidgets.QFrame(SearchConfirmationAskingWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.QuestionLabel = QtWidgets.QLabel(SearchConfirmationAskingWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuestionLabel.sizePolicy().hasHeightForWidth())
        self.QuestionLabel.setSizePolicy(sizePolicy)
        self.QuestionLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.QuestionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.QuestionLabel.setWordWrap(True)
        self.QuestionLabel.setObjectName("QuestionLabel")
        self.verticalLayout.addWidget(self.QuestionLabel)
        self.SuggestionLabel = QtWidgets.QLabel(SearchConfirmationAskingWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuggestionLabel.sizePolicy().hasHeightForWidth())
        self.SuggestionLabel.setSizePolicy(sizePolicy)
        self.SuggestionLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SuggestionLabel.setFont(font)
        self.SuggestionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SuggestionLabel.setWordWrap(True)
        self.SuggestionLabel.setObjectName("SuggestionLabel")
        self.verticalLayout.addWidget(self.SuggestionLabel)
        self.hor = QtWidgets.QHBoxLayout()
        self.hor.setObjectName("hor")
        self.SearchAgainPushButton = QtWidgets.QPushButton(SearchConfirmationAskingWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchAgainPushButton.sizePolicy().hasHeightForWidth())
        self.SearchAgainPushButton.setSizePolicy(sizePolicy)
        self.SearchAgainPushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SearchAgainPushButton.setObjectName("SearchAgainPushButton")
        self.hor.addWidget(self.SearchAgainPushButton)
        self.CorrectPushButton = QtWidgets.QPushButton(SearchConfirmationAskingWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CorrectPushButton.sizePolicy().hasHeightForWidth())
        self.CorrectPushButton.setSizePolicy(sizePolicy)
        self.CorrectPushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.CorrectPushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CorrectPushButton.setObjectName("CorrectPushButton")
        self.CorrectPushButton.setFocus() #Set the initial focus of the GUI.
        self.CorrectPushButton.setStyleSheet("background-color: rgb(176, 202, 220);")
        self.hor.addWidget(self.CorrectPushButton)
        self.verticalLayout.addLayout(self.hor)

        self.retranslateUi(SearchConfirmationAskingWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchConfirmationAskingWindow)


    def retranslateUi(self, SearchConfirmationAskingWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchConfirmationAskingWindow.setWindowTitle(_translate("SearchConfirmationAskingWindow", "Form"))
        self.CompletionLabel.setText(_translate("SearchConfirmationAskingWindow", "ARUCO markers search completed!"))
        self.QuestionLabel.setText(_translate("SearchConfirmationAskingWindow", "Has the localization been performed correctly?"))
        self.SuggestionLabel.setText(_translate("SearchConfirmationAskingWindow", "If not, try moving the box and the clock or changing lightning in the room and perform the search again "))
        self.SearchAgainPushButton.setText(_translate("SearchConfirmationAskingWindow", "Search Again"))
        self.CorrectPushButton.setText(_translate("SearchConfirmationAskingWindow", "Correct"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchConfirmationAskingWindow = QtWidgets.QWidget()
    ui = Ui_SearchConfirmationAskingWindow()
    ui.setupUi(SearchConfirmationAskingWindow)
    SearchConfirmationAskingWindow.show()
    sys.exit(app.exec_())

