# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

GUI_PKG_DIR = '/home/luca/tiago_public_ws/src/chess_gui'

class Ui_StartMarkersSearch(object):
    def setupUi(self, StartMarkersSearch):
        StartMarkersSearch.setObjectName("StartMarkersSearch")
        StartMarkersSearch.resize(630, 599)
        self.verticalLayout = QtWidgets.QVBoxLayout(StartMarkersSearch)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ClockInstructionsLabel = QtWidgets.QLabel(StartMarkersSearch)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ClockInstructionsLabel.setFont(font)
        self.ClockInstructionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ClockInstructionsLabel.setObjectName("ClockInstructionsLabel")
        self.verticalLayout.addWidget(self.ClockInstructionsLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ClockChecklist = QtWidgets.QListWidget(StartMarkersSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClockChecklist.sizePolicy().hasHeightForWidth())
        self.ClockChecklist.setSizePolicy(sizePolicy)
        self.ClockChecklist.setMaximumSize(QtCore.QSize(400, 140))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ClockChecklist.setFont(font)
        self.ClockChecklist.setAutoFillBackground(False)
        self.ClockChecklist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ClockChecklist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ClockChecklist.setViewMode(QtWidgets.QListView.ListMode)
        self.ClockChecklist.setWordWrap(True)
        self.ClockChecklist.setObjectName("ClockChecklist")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/black_pawn2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.ClockChecklist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.ClockChecklist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.ClockChecklist.addItem(item)
        self.horizontalLayout_2.addWidget(self.ClockChecklist)
        self.ClockImage1Label = QtWidgets.QLabel(StartMarkersSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClockImage1Label.sizePolicy().hasHeightForWidth())
        self.ClockImage1Label.setSizePolicy(sizePolicy)
        self.ClockImage1Label.setMaximumSize(QtCore.QSize(140, 140))
        self.ClockImage1Label.setText("")
        self.ClockImage1Label.setPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/clock_positioning_from_above.jpg"))
        self.ClockImage1Label.setScaledContents(True)
        self.ClockImage1Label.setObjectName("ClockImage1Label")
        self.horizontalLayout_2.addWidget(self.ClockImage1Label)
        self.ClockImage2Label = QtWidgets.QLabel(StartMarkersSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClockImage2Label.sizePolicy().hasHeightForWidth())
        self.ClockImage2Label.setSizePolicy(sizePolicy)
        self.ClockImage2Label.setMaximumSize(QtCore.QSize(140, 140))
        self.ClockImage2Label.setText("")
        self.ClockImage2Label.setPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/clock_positioning_detail.jpg"))
        self.ClockImage2Label.setScaledContents(True)
        self.ClockImage2Label.setObjectName("ClockImage2Label")
        self.horizontalLayout_2.addWidget(self.ClockImage2Label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(StartMarkersSearch)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.BoxInstructionsLabel = QtWidgets.QLabel(StartMarkersSearch)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.BoxInstructionsLabel.setFont(font)
        self.BoxInstructionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BoxInstructionsLabel.setObjectName("BoxInstructionsLabel")
        self.verticalLayout.addWidget(self.BoxInstructionsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BoxChecklist = QtWidgets.QListWidget(StartMarkersSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BoxChecklist.sizePolicy().hasHeightForWidth())
        self.BoxChecklist.setSizePolicy(sizePolicy)
        self.BoxChecklist.setMaximumSize(QtCore.QSize(400, 140))
        self.BoxChecklist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.BoxChecklist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.BoxChecklist.setWordWrap(True)
        self.BoxChecklist.setObjectName("BoxChecklist")
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.BoxChecklist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.BoxChecklist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.BoxChecklist.addItem(item)
        self.horizontalLayout.addWidget(self.BoxChecklist)
        self.BoxImage1Label = QtWidgets.QLabel(StartMarkersSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BoxImage1Label.sizePolicy().hasHeightForWidth())
        self.BoxImage1Label.setSizePolicy(sizePolicy)
        self.BoxImage1Label.setMaximumSize(QtCore.QSize(140, 140))
        self.BoxImage1Label.setText("")
        self.BoxImage1Label.setPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/box_positioning_from_above.jpg"))
        self.BoxImage1Label.setScaledContents(True)
        self.BoxImage1Label.setObjectName("BoxImage1Label")
        self.horizontalLayout.addWidget(self.BoxImage1Label)
        self.BoxImage2Label = QtWidgets.QLabel(StartMarkersSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BoxImage2Label.sizePolicy().hasHeightForWidth())
        self.BoxImage2Label.setSizePolicy(sizePolicy)
        self.BoxImage2Label.setMaximumSize(QtCore.QSize(140, 140))
        self.BoxImage2Label.setText("")
        self.BoxImage2Label.setPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/box_positioning_detail.jpg"))
        self.BoxImage2Label.setScaledContents(True)
        self.BoxImage2Label.setObjectName("BoxImage2Label")
        self.horizontalLayout.addWidget(self.BoxImage2Label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(StartMarkersSearch)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.PiecesInstructionsLabel = QtWidgets.QLabel(StartMarkersSearch)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PiecesInstructionsLabel.setFont(font)
        self.PiecesInstructionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PiecesInstructionsLabel.setObjectName("PiecesInstructionsLabel")
        self.verticalLayout.addWidget(self.PiecesInstructionsLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PiecesChecklist = QtWidgets.QListWidget(StartMarkersSearch)
        self.PiecesChecklist.setEnabled(True)
        self.PiecesChecklist.setMaximumSize(QtCore.QSize(400, 140))
        self.PiecesChecklist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PiecesChecklist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PiecesChecklist.setWordWrap(True)
        self.PiecesChecklist.setObjectName("PiecesChecklist")
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.PiecesChecklist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.PiecesChecklist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.PiecesChecklist.addItem(item)
        self.horizontalLayout_3.addWidget(self.PiecesChecklist)
        self.PiecesImage1Label = QtWidgets.QLabel(StartMarkersSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PiecesImage1Label.sizePolicy().hasHeightForWidth())
        self.PiecesImage1Label.setSizePolicy(sizePolicy)
        self.PiecesImage1Label.setMaximumSize(QtCore.QSize(140, 140))
        self.PiecesImage1Label.setText("")
        self.PiecesImage1Label.setPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/pieces_positioning_from_above.jpg"))
        self.PiecesImage1Label.setScaledContents(True)
        self.PiecesImage1Label.setObjectName("PiecesImage1Label")
        self.horizontalLayout_3.addWidget(self.PiecesImage1Label)
        self.PiecesImage2Label = QtWidgets.QLabel(StartMarkersSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PiecesImage2Label.sizePolicy().hasHeightForWidth())
        self.PiecesImage2Label.setSizePolicy(sizePolicy)
        self.PiecesImage2Label.setMaximumSize(QtCore.QSize(140, 140))
        self.PiecesImage2Label.setText("")
        self.PiecesImage2Label.setPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/pieces_positioning_detail.jpg"))
        self.PiecesImage2Label.setScaledContents(True)
        self.PiecesImage2Label.setObjectName("PiecesImage2Label")
        self.horizontalLayout_3.addWidget(self.PiecesImage2Label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.StartSearchPushButton = QtWidgets.QPushButton(StartMarkersSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartSearchPushButton.sizePolicy().hasHeightForWidth())
        self.StartSearchPushButton.setSizePolicy(sizePolicy)
        self.StartSearchPushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.StartSearchPushButton.setMaximumSize(QtCore.QSize(1000, 300))
        self.StartSearchPushButton.setObjectName("StartSearchPushButton")
        self.StartSearchPushButton.setStyleSheet("background-color: rgb(176, 202, 220);")
        self.verticalLayout.addWidget(self.StartSearchPushButton)

        self.retranslateUi(StartMarkersSearch)
        QtCore.QMetaObject.connectSlotsByName(StartMarkersSearch)


    def retranslateUi(self, StartMarkersSearch):
        _translate = QtCore.QCoreApplication.translate
        StartMarkersSearch.setWindowTitle(_translate("StartMarkersSearch", "Form"))
        self.ClockInstructionsLabel.setText(_translate("StartMarkersSearch", "Clock positioning instructions"))
        __sortingEnabled = self.ClockChecklist.isSortingEnabled()
        self.ClockChecklist.setSortingEnabled(False)
        item = self.ClockChecklist.item(0)
        item.setText(_translate("StartMarkersSearch", "Place the clock on the right side of the chessboard from TIAGo\'s side."))
        item = self.ClockChecklist.item(1)
        item.setText(_translate("StartMarkersSearch", "The ARUCO marker number 100 has to be fixed on the clock."))
        item = self.ClockChecklist.item(2)
        item.setText(_translate("StartMarkersSearch", "Fix the marker on the button of the clock closer to TIAGo, in the terminal part of the button (see Figure)."))
        self.ClockChecklist.setSortingEnabled(__sortingEnabled)
        self.BoxInstructionsLabel.setText(_translate("StartMarkersSearch", "Box positioning instructions"))
        __sortingEnabled = self.BoxChecklist.isSortingEnabled()
        self.BoxChecklist.setSortingEnabled(False)
        item = self.BoxChecklist.item(0)
        item.setText(_translate("StartMarkersSearch", "Place the box that will contain the captured pieces on the left side of the chessboard from TIAGo\'s side."))
        item = self.BoxChecklist.item(1)
        item.setText(_translate("StartMarkersSearch", "The ARUCO marker number 300 has to be fixed on the box."))
        item = self.BoxChecklist.item(2)
        item.setText(_translate("StartMarkersSearch", "Fix the marker on the border of the box closer to TIAGo (see Figure)."))
        self.BoxChecklist.setSortingEnabled(__sortingEnabled)
        self.PiecesInstructionsLabel.setText(_translate("StartMarkersSearch", "Pieces positioning Instructions"))
        __sortingEnabled = self.PiecesChecklist.isSortingEnabled()
        self.PiecesChecklist.setSortingEnabled(False)
        item = self.PiecesChecklist.item(0)
        item.setText(_translate("StartMarkersSearch", "Place the pieces in their starting position on the chessboard."))
        item = self.PiecesChecklist.item(1)
        item.setText(_translate("StartMarkersSearch", "Place them carefully in the center of the squares and ask the opponent to always do it during the game."))
        item = self.PiecesChecklist.item(2)
        item.setText(_translate("StartMarkersSearch", "Place the knights facing the opposite border of the chessboard (see Figure)."))
        self.PiecesChecklist.setSortingEnabled(__sortingEnabled)
        self.StartSearchPushButton.setText(_translate("StartMarkersSearch", "Start ARUCO Markers Search"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartMarkersSearch = QtWidgets.QWidget()
    ui = Ui_StartMarkersSearch()
    ui.setupUi(StartMarkersSearch)
    StartMarkersSearch.show()
    sys.exit(app.exec_())

