# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from std_msgs.msg import String

GUI_PKG_DIR = '/home/luca/tiago_public_ws/src/chess_gui'

class Ui_StartSegmentation(object):
    def setupUi(self, StartSegmentation, color): #, color
        StartSegmentation.setObjectName("StartSegmentation")
        StartSegmentation.resize(536, 456)
        self.verticalLayout = QtWidgets.QVBoxLayout(StartSegmentation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ColorChoiceLabel = QtWidgets.QLabel(StartSegmentation)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ColorChoiceLabel.setFont(font)
        self.ColorChoiceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ColorChoiceLabel.setObjectName("ColorChoiceLabel")
        self.verticalLayout_2.addWidget(self.ColorChoiceLabel)
        self.IndicationLabel = QtWidgets.QLabel(StartSegmentation)
        self.IndicationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.IndicationLabel.setWordWrap(True)
        self.IndicationLabel.setObjectName("IndicationLabel")
        self.verticalLayout_2.addWidget(self.IndicationLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.GoBackButton = QtWidgets.QPushButton(StartSegmentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoBackButton.sizePolicy().hasHeightForWidth())
        self.GoBackButton.setSizePolicy(sizePolicy)
        self.GoBackButton.setMaximumSize(QtCore.QSize(100, 50))
        self.GoBackButton.setObjectName("GoBackButton")
        self.horizontalLayout.addWidget(self.GoBackButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(StartSegmentation)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.InstructionsLabel = QtWidgets.QLabel(StartSegmentation)
        self.InstructionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InstructionsLabel.setObjectName("InstructionsLabel")
        self.verticalLayout.addWidget(self.InstructionsLabel)
        self.Checklist = QtWidgets.QListWidget(StartSegmentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Checklist.sizePolicy().hasHeightForWidth())
        self.Checklist.setSizePolicy(sizePolicy)
        self.Checklist.setMaximumSize(QtCore.QSize(16777215, 1000))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Checklist.setFont(font)
        self.Checklist.setAutoFillBackground(False)
        self.Checklist.setViewMode(QtWidgets.QListView.ListMode)
        self.Checklist.setWordWrap(True)
        self.Checklist.setObjectName("Checklist")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(GUI_PKG_DIR + "/images/black_pawn2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.Checklist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.Checklist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.Checklist.addItem(item)
        self.verticalLayout.addWidget(self.Checklist)
        self.pushButton = QtWidgets.QPushButton(StartSegmentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(1000, 100))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setFocus() #Set the initial focus of the GUI
        self.pushButton.setStyleSheet("background-color: rgb(176, 202, 220);")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(StartSegmentation, color) #color
        QtCore.QMetaObject.connectSlotsByName(StartSegmentation)

    def retranslateUi(self, StartSegmentation, color):
        _translate = QtCore.QCoreApplication.translate
        StartSegmentation.setWindowTitle(_translate("StartSegmentation", "Form"))
        self.ColorChoiceLabel.setText(_translate("StartSegmentation", "TIAGo is playing with " + str(color)))
        self.IndicationLabel.setText(_translate("StartSegmentation", "If not, go back and select the right color"))
        self.GoBackButton.setText(_translate("StartSegmentation", "Go Back"))
        self.InstructionsLabel.setText(_translate("StartSegmentation", "Chessboard positioning istructions"))
        __sortingEnabled = self.Checklist.isSortingEnabled()
        self.Checklist.setSortingEnabled(False)
        item = self.Checklist.item(0)
        item.setText(_translate("StartSegmentation", "Place the empty chessboard on the table in front of TIAGo"))
        item = self.Checklist.item(1)
        item.setText(_translate("StartSegmentation", "Make sure that the whole chessboard is seen by TIAGo"))
        item = self.Checklist.item(2)
        item.setText(_translate("StartSegmentation", "Make sure that nothing is over the chessboard "))
        self.Checklist.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("StartSegmentation", "Start Chessboard Segmentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartSegmentation = QtWidgets.QWidget()
    ui = Ui_StartSegmentation()
    ui.setupUi(StartSegmentation, 'WHITE')
    StartSegmentation.show()
    sys.exit(app.exec_())

